#!/usr/bin/env bash
# updates the IP addresses in /etc/hosts for localhost and facebook.com

HOSTS_FILE="/etc/hosts"

sudo sed -i -e 's/^/#/' $HOSTS_FILE
{
    sudo echo ""
    sudo echo "127.0.0.2 localhost"
    sudo echo "8.8.8.8 facebook.com"
} >> $HOSTS_FILE